import '../model/model.dart';

/// Canvas701.com'dan çekilen gerçek veriler
/// Base URL: https://www.canvas701.com
class Canvas701Data {
  Canvas701Data._();

  /// Base URL
  static const String baseUrl = 'https://www.canvas701.com';

  /// Görsel URL oluştur
  static String imageUrl(String slug) => '$baseUrl/upload/images/$slug.jpg';

  /// Ürün URL oluştur
  static String productUrl(String slug) => '$baseUrl/$slug';

  /// Kategori URL oluştur
  static String categoryUrl(String slug) => '$baseUrl/kanvas-tablolar/$slug';

  /// Kategoriler - Gerçek veriler
  static const List<Category> categories = [
    Category(
      id: 'cat-araba',
      name: 'Araba',
      slug: 'araba',
      imageUrl: '$baseUrl/kanvas-tablolar/araba',
      productCount: 30,
      sortOrder: 1,
    ),
    Category(
      id: 'cat-ataturk',
      name: 'Atatürk',
      slug: 'ataturk',
      imageUrl: '$baseUrl/kanvas-tablolar/ataturk',
      productCount: 37,
      sortOrder: 2,
    ),
    Category(
      id: 'cat-bust-heykel',
      name: 'Büst & Heykel',
      slug: 'bust-heykel',
      imageUrl: '$baseUrl/kanvas-tablolar/bust-heykel',
      productCount: 31,
      sortOrder: 3,
    ),
    Category(
      id: 'cat-deniz-canlilari',
      name: 'Deniz Canlıları',
      slug: 'deniz-canlilari',
      imageUrl: '$baseUrl/kanvas-tablolar/deniz-canlilari',
      productCount: 31,
      sortOrder: 4,
    ),
    Category(
      id: 'cat-dini',
      name: 'Dini',
      slug: 'dini',
      imageUrl: '$baseUrl/kanvas-tablolar/dini',
      productCount: 6,
      sortOrder: 5,
    ),
    Category(
      id: 'cat-dizi-film',
      name: 'Dizi & Film & Karakterler',
      slug: 'dizi-film-karakterler',
      imageUrl: '$baseUrl/kanvas-tablolar/dizi-film-karakterler',
      productCount: 151,
      sortOrder: 6,
    ),
    Category(
      id: 'cat-doga',
      name: 'Doğa & Hayvan',
      slug: 'doga',
      imageUrl: '$baseUrl/kanvas-tablolar/doga',
      productCount: 110,
      sortOrder: 7,
    ),
    Category(
      id: 'cat-kis',
      name: 'Kış',
      slug: 'kis',
      imageUrl: '$baseUrl/kanvas-tablolar/kis',
      productCount: 35,
      sortOrder: 8,
    ),
    Category(
      id: 'cat-manzara',
      name: 'Manzara',
      slug: 'manzara',
      imageUrl: '$baseUrl/kanvas-tablolar/manzara',
      productCount: 232,
      sortOrder: 9,
    ),
    Category(
      id: 'cat-marka',
      name: 'Marka',
      slug: 'marka',
      imageUrl: '$baseUrl/kanvas-tablolar/marka',
      productCount: 41,
      sortOrder: 10,
    ),
    Category(
      id: 'cat-melek',
      name: 'Melek',
      slug: 'melek',
      imageUrl: '$baseUrl/kanvas-tablolar/melek',
      productCount: 8,
      sortOrder: 11,
    ),
    Category(
      id: 'cat-minimalist',
      name: 'Minimalist',
      slug: 'minimalist',
      imageUrl: '$baseUrl/kanvas-tablolar/minimalist',
      productCount: 33,
      sortOrder: 12,
    ),
    Category(
      id: 'cat-motorsiklet',
      name: 'Motorsiklet',
      slug: 'motorsiklet',
      imageUrl: '$baseUrl/kanvas-tablolar/motorsiklet',
      productCount: 13,
      sortOrder: 13,
    ),
    Category(
      id: 'cat-mutfak',
      name: 'Mutfak ve Yemek',
      slug: 'mutfak-ve-yemek',
      imageUrl: '$baseUrl/kanvas-tablolar/mutfak-ve-yemek',
      productCount: 54,
      sortOrder: 14,
    ),
    Category(
      id: 'cat-neon',
      name: 'Neon & Yazı',
      slug: 'neon-yazi',
      imageUrl: '$baseUrl/kanvas-tablolar/neon-yazi',
      productCount: 37,
      sortOrder: 15,
    ),
    Category(
      id: 'cat-nu',
      name: 'Nu',
      slug: 'nu',
      imageUrl: '$baseUrl/kanvas-tablolar/nu',
      productCount: 12,
      sortOrder: 16,
    ),
    Category(
      id: 'cat-oyun',
      name: 'Oyun & Karakterler',
      slug: 'oyun-karakterler',
      imageUrl: '$baseUrl/kanvas-tablolar/oyun-karakterler',
      productCount: 15,
      sortOrder: 17,
    ),
    Category(
      id: 'cat-perspektif',
      name: 'Perspektif',
      slug: 'perspektif',
      imageUrl: '$baseUrl/kanvas-tablolar/perspektif',
      productCount: 19,
      sortOrder: 18,
    ),
    Category(
      id: 'cat-popart',
      name: 'Popart',
      slug: 'popart',
      imageUrl: '$baseUrl/kanvas-tablolar/popart',
      productCount: 12,
      sortOrder: 19,
    ),
    Category(
      id: 'cat-siyah-beyaz',
      name: 'Siyah & Beyaz',
      slug: 'siyah-beyaz',
      imageUrl: '$baseUrl/kanvas-tablolar/siyah-beyaz',
      productCount: 28,
      sortOrder: 20,
    ),
    Category(
      id: 'cat-spor',
      name: 'Spor',
      slug: 'spor',
      imageUrl: '$baseUrl/kanvas-tablolar/spor',
      productCount: 27,
      sortOrder: 21,
    ),
    Category(
      id: 'cat-surrealist',
      name: 'Sürrealist / Çizim',
      slug: 'surrealist-cizim',
      imageUrl: '$baseUrl/kanvas-tablolar/surrealist-cizim',
      productCount: 262,
      sortOrder: 22,
    ),
    Category(
      id: 'cat-sehir',
      name: 'Şehir',
      slug: 'sehir',
      imageUrl: '$baseUrl/kanvas-tablolar/sehir',
      productCount: 34,
      sortOrder: 23,
    ),
    Category(
      id: 'cat-tarih',
      name: 'Tarih',
      slug: 'tarih',
      imageUrl: '$baseUrl/kanvas-tablolar/tarih',
      productCount: 24,
      sortOrder: 24,
    ),
    Category(
      id: 'cat-teknoloji',
      name: 'Teknoloji',
      slug: 'teknoloji',
      imageUrl: '$baseUrl/kanvas-tablolar/teknoloji',
      productCount: 18,
      sortOrder: 25,
    ),
    Category(
      id: 'cat-turkculuk',
      name: 'Türkçülük',
      slug: 'turkculuk',
      imageUrl: '$baseUrl/kanvas-tablolar/turkculuk',
      productCount: 8,
      sortOrder: 26,
    ),
    Category(
      id: 'cat-unlenmis',
      name: 'Ünlenmiş Tablolar',
      slug: 'unlenmis-tablolar',
      imageUrl: '$baseUrl/kanvas-tablolar/unlenmis-tablolar',
      productCount: 20,
      sortOrder: 27,
    ),
    Category(
      id: 'cat-unlu-sanatci',
      name: 'Ünlü Sanatçı',
      slug: 'unlu-sanatcilar',
      imageUrl: '$baseUrl/kanvas-tablolar/unlu-sanatcilar',
      productCount: 20,
      sortOrder: 28,
    ),
    Category(
      id: 'cat-uzay',
      name: 'Uzay',
      slug: 'uzay',
      imageUrl: '$baseUrl/kanvas-tablolar/uzay',
      productCount: 49,
      sortOrder: 29,
    ),
    Category(
      id: 'cat-vintage',
      name: 'Vintage',
      slug: 'vintage',
      imageUrl: '$baseUrl/kanvas-tablolar/vintage',
      productCount: 26,
      sortOrder: 30,
    ),
    Category(
      id: 'cat-yesilcam',
      name: 'Yeşilçam',
      slug: 'yesilcam',
      imageUrl: '$baseUrl/kanvas-tablolar/yesilcam',
      productCount: 14,
      sortOrder: 31,
    ),
  ];

  /// Boyut seçenekleri - Canvas701 standart boyutları
  static const List<ProductSize> defaultSizes = [
    ProductSize(id: 'size-1', name: '30x40 cm', width: 30, height: 40, price: 299.90),
    ProductSize(id: 'size-2', name: '40x60 cm', width: 40, height: 60, price: 399.90),
    ProductSize(id: 'size-3', name: '50x70 cm', width: 50, height: 70, price: 449.90),
    ProductSize(id: 'size-4', name: '60x90 cm', width: 60, height: 90, price: 549.90),
    ProductSize(id: 'size-5', name: '70x100 cm', width: 70, height: 100, price: 649.90),
  ];

  /// Çok Satan Ürünler - Canvas701.com gerçek veriler
  static List<Product> get bestsellers => [
    Product(
      id: 'C701-1423',
      code: 'C701-1423',
      name: 'Kıvrımlı Nehir Kanvas Tablo',
      description: 'Kıvrımlı nehir manzarasının huzur verici görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2022/09/kivrimli-nehir-3.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-manzara'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
    ),
    Product(
      id: 'C701-1433',
      code: 'C701-1433',
      name: 'Santorini ve Begonvil Kanvas Tablo',
      description: 'Santorini adası ve begonvil çiçeklerinin romantik manzarası.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2022/09/santorini-ve-begonvil-3.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-manzara', 'cat-sehir'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 38)),
    ),
    Product(
      id: 'C701-1469',
      code: 'C701-1469',
      name: 'Ebruli Sanatı Renkleri Kanvas Tablo',
      description: 'Geleneksel ebru sanatının renkli ve etkileyici kompozisyonu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2022/10/ebruli-sanati-3.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-surrealist'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 36)),
    ),
    Product(
      id: 'C701-1490',
      code: 'C701-1490',
      name: 'Kalifornia Kanvas Tablo',
      description: 'Kaliforniya sahil manzarasının huzur verici görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2022/11/kalifornia-3.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-manzara'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 33)),
    ),
    Product(
      id: 'C701-118',
      code: 'C701-118',
      name: 'Karlar İçinde Melek Kanvas Tablo',
      description: 'Karların arasında melek figürü içeren etkileyici kış temalı tablo.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2018/10/angel12.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-kis', 'cat-melek'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
    ),
    Product(
      id: 'C701-1096',
      code: 'C701-1096',
      name: 'Yağlı Boya Yelkenli Gemiler Kanvas Tablo',
      description: 'Yağlı boya tekniğiyle çizilmiş yelkenli gemiler tablosu.',
      price: 449.90,
      images: ['$baseUrl/yagli-boya-yelkenki-gemiler-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-manzara'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    Product(
      id: 'C701-1031',
      code: 'C701-1031',
      name: 'Bodrum Evleri Kanvas Tablo',
      description: 'Bodrum\'un beyaz evlerini yansıtan etkileyici tablo.',
      price: 449.90,
      images: ['$baseUrl/bodrum-evleri-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-manzara', 'cat-sehir'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 28)),
    ),
    Product(
      id: 'C701-564',
      code: 'C701-564',
      name: 'Tünel Kanvas Tablo',
      description: 'Perspektif illüzyonu yaratan tünel görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2019/08/torii-mockup-instagram-logolu.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-perspektif'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
    ),
    Product(
      id: 'C701-1159',
      code: 'C701-1159',
      name: 'Alexandre Cabanel Düşmüş Melek Kanvas Tablo',
      description: 'Alexandre Cabanel\'in ünlü Düşmüş Melek eserinin reprodüksiyonu.',
      price: 449.90,
      images: ['$baseUrl/alexandre-cabanel-dusmus-melek-kanvas-tablo-1'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-melek', 'cat-unlenmis'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    Product(
      id: 'C701-405',
      code: 'C701-405',
      name: 'Muhammed Ali Kanvas Tablo',
      description: 'Efsanevi boksör Muhammed Ali\'nin ikonik portresi.',
      price: 449.90,
      images: ['$baseUrl/muhammed-ali-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-spor', 'cat-unlu-sanatci'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
    ),
    Product(
      id: 'C701-943',
      code: 'C701-943',
      name: 'Venüs\'ün Doğuşu, Sandro Botticelli Kanvas Tablo',
      description: 'Sandro Botticelli\'nin meşhur Venüs\'ün Doğuşu eserinin reprodüksiyonu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2020/04/venus-un-dogusu-sandro-botticelli-1485.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-unlenmis', 'cat-unlu-sanatci'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
    ),
    Product(
      id: 'C701-624',
      code: 'C701-624',
      name: 'Asker Atatürk Kanvas Tablo',
      description: 'Mustafa Kemal Atatürk\'ün asker üniformalı portresi.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2021/09/asker-ataturk-2-logolu.jpg'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-ataturk'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
    ),
    Product(
      id: 'C701-413',
      code: 'C701-413',
      name: 'Joker Kanvas Tablo',
      description: 'DC Comics\'in ikonik karakteri Joker\'in etkileyici portresi.',
      price: 449.90,
      images: ['$baseUrl/joker-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-dizi-film'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    Product(
      id: 'C701-306',
      code: 'C701-306',
      name: 'Software Development Kanvas Tablo',
      description: 'Yazılım geliştirme temalı modern tablo.',
      price: 449.90,
      images: ['$baseUrl/software-development-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-teknoloji'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
    ),
    Product(
      id: 'C701-232',
      code: 'C701-232',
      name: 'Van Gogh Yıldızlı Gece Kanvas Tablo',
      description: 'Vincent van Gogh\'un dünyaca ünlü Yıldızlı Gece eserinin reprodüksiyonu.',
      price: 449.90,
      images: ['$baseUrl/van-gogh-yildizli-gece-kanvas-tablo'],
      collectionId: 'col-bestseller',
      categoryIds: ['cat-unlenmis', 'cat-unlu-sanatci'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
  ];

  /// Son Eklenen Ürünler - Canvas701.com gerçek veriler
  static List<Product> get newArrivals => [
    Product(
      id: 'C701-1636',
      code: 'C701-1636',
      name: 'Gucci Mağaza Önü Kanvas Tablo',
      description: 'Gucci marka mağaza cephesinin etkileyici görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/gucci-magaza-onu-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Product(
      id: 'C701-1635',
      code: 'C701-1635',
      name: 'Gucci Ayakkabı Kanvas Tablo',
      description: 'Gucci marka ayakkabıların sanatsal sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/gucci-ayakkabi-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Product(
      id: 'C701-1634',
      code: 'C701-1634',
      name: 'Chanel Parfüm Siyah Beyaz Kanvas Tablo',
      description: 'Chanel parfümünün siyah beyaz artistik fotoğrafı.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/chanel-parfum-siyah-beyaz-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka', 'cat-siyah-beyaz'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Product(
      id: 'C701-1633',
      code: 'C701-1633',
      name: 'Nike Uçan Ayakkabılar Kanvas Tablo',
      description: 'Nike ayakkabıların dinamik ve enerjik sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/ucan-ayakkanilar-nike-3-min_1.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka', 'cat-spor'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Product(
      id: 'C701-1631',
      code: 'C701-1631',
      name: 'Ruj Süren Kadın Kanvas Tablo',
      description: 'Ruj süren kadın figürünün zarif portresi.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/ruj-suren-kadin-3.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-surrealist'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    Product(
      id: 'C701-1630',
      code: 'C701-1630',
      name: 'Nike Modeli Kanvas Tablo',
      description: 'Nike marka modelinin etkileyici sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/nike-modeli-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka', 'cat-spor'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    Product(
      id: 'C701-1629',
      code: 'C701-1629',
      name: 'Nike Mağazası Kanvas Tablo',
      description: 'Nike mağazasının modern ve dinamik görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/nike-magazasi-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Product(
      id: 'C701-1627',
      code: 'C701-1627',
      name: 'Kaykay ve Adidas Kanvas Tablo',
      description: 'Kaykay ve Adidas marka kombinasyonu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/kaykay-ve-adidas-3.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka', 'cat-spor'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Product(
      id: 'C701-1626',
      code: 'C701-1626',
      name: 'Kadın Marka Yüzü Kanvas Tablo',
      description: 'Kadın ve marka temasının sanatsal sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/kadin-bir-marka-yuzu-3.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Product(
      id: 'C701-1628',
      code: 'C701-1628',
      name: 'Kaykayla Dans Kanvas Tablo',
      description: 'Kaykay üzerinde dans eden figür.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/kaykayla-dans-3-min.jpg'],
      collectionId: 'col-new',
      categoryIds: ['cat-spor', 'cat-surrealist'],
      availableSizes: defaultSizes,
      isNew: true,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
  ];

  /// Marka/Lüks Kategorisi Ürünleri
  static List<Product> get luxuryProducts => [
    Product(
      id: 'C701-1636',
      code: 'C701-1636',
      name: 'Gucci Mağaza Önü Kanvas Tablo',
      description: 'Gucci marka mağaza cephesinin etkileyici görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/gucci-magaza-onu-3-min.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    Product(
      id: 'C701-1635',
      code: 'C701-1635',
      name: 'Gucci Ayakkabı Kanvas Tablo',
      description: 'Gucci marka ayakkabıların sanatsal sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/gucci-ayakkabi-3-min.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 55)),
    ),
    Product(
      id: 'C701-1634',
      code: 'C701-1634',
      name: 'Chanel Parfüm Siyah Beyaz Kanvas Tablo',
      description: 'Chanel parfümünün siyah beyaz artistik fotoğrafı.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/chanel-parfum-siyah-beyaz-3-min.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka', 'cat-siyah-beyaz'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
    ),
    Product(
      id: 'C701-1630',
      code: 'C701-1630',
      name: 'Nike Modeli Kanvas Tablo',
      description: 'Nike marka modelinin etkileyici sunumu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/nike-modeli-3-min.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka', 'cat-spor'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
    ),
    Product(
      id: 'C701-1629',
      code: 'C701-1629',
      name: 'Nike Mağazası Kanvas Tablo',
      description: 'Nike mağazasının modern ve dinamik görseli.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/nike-magazasi-3-min.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
    ),
    Product(
      id: 'C701-1627',
      code: 'C701-1627',
      name: 'Kaykay ve Adidas Kanvas Tablo',
      description: 'Kaykay ve Adidas marka kombinasyonu.',
      price: 449.90,
      images: ['https://www.canvas701.com/upload/2023/06/kaykay-ve-adidas-3.jpg'],
      collectionId: 'col-luxury',
      categoryIds: ['cat-marka', 'cat-spor'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
    ),
  ];

  /// Atatürk Kategorisi Ürünleri
  static List<Product> get ataturkProducts => [
    Product(
      id: 'C701-624',
      code: 'C701-624',
      name: 'Asker Atatürk Kanvas Tablo',
      description: 'Mustafa Kemal Atatürk\'ün asker üniformalı portresi.',
      price: 449.90,
      images: ['$baseUrl/asker-ataturk-kanvas-tablo'],
      collectionId: 'col-ataturk',
      categoryIds: ['cat-ataturk'],
      availableSizes: defaultSizes,
      isBestseller: true,
      createdAt: DateTime.now().subtract(const Duration(days: 100)),
    ),
    Product(
      id: 'C701-80',
      code: 'C701-80',
      name: 'Türk Bayrağı ve Atatürk Kanvas Tablo',
      description: 'Türk bayrağı önünde Atatürk portresi.',
      price: 449.90,
      images: ['$baseUrl/turk-bayragi-ve-ataturk-kanvas-tablo'],
      collectionId: 'col-ataturk',
      categoryIds: ['cat-ataturk', 'cat-turkculuk'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 95)),
    ),
    Product(
      id: 'C701-1225',
      code: 'C701-1225',
      name: 'Yüksek Çözünürlüklü Atatürk Kanvas Tablo',
      description: 'Yüksek kaliteli Atatürk portresi.',
      price: 449.90,
      images: ['$baseUrl/yuksek-cozunurluklu-ataturk-kanvas-tablo'],
      collectionId: 'col-ataturk',
      categoryIds: ['cat-ataturk'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
    Product(
      id: 'C701-70',
      code: 'C701-70',
      name: 'Atatürk Kanvas Tablo',
      description: 'Klasik Atatürk portresi.',
      price: 449.90,
      images: ['$baseUrl/ataturk-kanvas-tablo-2'],
      collectionId: 'col-ataturk',
      categoryIds: ['cat-ataturk'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 85)),
    ),
    Product(
      id: 'C701-857',
      code: 'C701-857',
      name: 'Mustafa Kemal Atatürk Özel Kanvas Tablo',
      description: 'Özel tasarım Atatürk portresi.',
      price: 449.90,
      images: ['$baseUrl/mustafa-kemal-ataturk-ozel-kanvas-tablo'],
      collectionId: 'col-ataturk',
      categoryIds: ['cat-ataturk'],
      availableSizes: defaultSizes,
      createdAt: DateTime.now().subtract(const Duration(days: 80)),
    ),
  ];

  /// Tüm ürünler
  static List<Product> get allProducts => [
    ...bestsellers,
    ...newArrivals,
    ...luxuryProducts,
    ...ataturkProducts,
  ];

  /// Koleksiyonlar
  static const List<Collection> collections = [
    Collection(
      id: 'col-bestseller',
      name: 'Çok Satanlar',
      description: 'En beğenilen ve en çok satan tablolarımız',
      imageUrl: '$baseUrl/cok-satilan-kanvas-tablolar',
      productCount: 40,
      isFeatured: true,
      sortOrder: 1,
    ),
    Collection(
      id: 'col-new',
      name: 'Son Eklenenler',
      description: 'Yeni eklenen kanvas tablolar',
      imageUrl: '$baseUrl/kanvas-tablolar',
      productCount: 20,
      isFeatured: true,
      sortOrder: 2,
    ),
    Collection(
      id: 'col-luxury',
      name: 'Marka & Lüks',
      description: 'Dünyaca ünlü markaların kanvas tabloları',
      imageUrl: '$baseUrl/kanvas-tablolar/marka',
      productCount: 41,
      isFeatured: true,
      sortOrder: 3,
    ),
    Collection(
      id: 'col-ataturk',
      name: 'Atatürk',
      description: 'Mustafa Kemal Atatürk kanvas tabloları',
      imageUrl: '$baseUrl/kanvas-tablolar/ataturk',
      productCount: 37,
      isFeatured: true,
      sortOrder: 4,
    ),
    Collection(
      id: 'col-art',
      name: 'Ünlü Tablolar',
      description: 'Dünyaca ünlü sanat eserlerinin reprodüksiyonları',
      imageUrl: '$baseUrl/kanvas-tablolar/unlenmis-tablolar',
      productCount: 20,
      isFeatured: true,
      sortOrder: 5,
    ),
  ];

  /// Toplam ürün sayısı (Canvas701.com'dan)
  static const int totalProductCount = 1388;
}
