// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dMAwLtxgzZqD8bPiYatX-ODkcDPAsSU',
    appId: '1:943279152524:web:d19d016c865063bd554aa9',
    messagingSenderId: '943279152524',
    projectId: 'canvas701',
    authDomain: 'canvas701.firebaseapp.com',
    storageBucket: 'canvas701.firebasestorage.app',
    measurementId: 'G-4E74B2FHZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7e-nEJT_FTMrQUy9_U0Qi6jxwIYf4yO4',
    appId: '1:943279152524:android:53ce00aec4c5d8a3554aa9',
    messagingSenderId: '943279152524',
    projectId: 'canvas701',
    storageBucket: 'canvas701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvY75MTcARLGAaSFJ1cYhctiIEcwf6v3s',
    appId: '1:943279152524:ios:190cf532c0b680cc554aa9',
    messagingSenderId: '943279152524',
    projectId: 'canvas701',
    storageBucket: 'canvas701.firebasestorage.app',
    iosBundleId: 'com.office701.canvas701',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvY75MTcARLGAaSFJ1cYhctiIEcwf6v3s',
    appId: '1:943279152524:ios:190cf532c0b680cc554aa9',
    messagingSenderId: '943279152524',
    projectId: 'canvas701',
    storageBucket: 'canvas701.firebasestorage.app',
    iosBundleId: 'com.office701.canvas701',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dMAwLtxgzZqD8bPiYatX-ODkcDPAsSU',
    appId: '1:943279152524:web:5232dc51d4c92fe4554aa9',
    messagingSenderId: '943279152524',
    projectId: 'canvas701',
    authDomain: 'canvas701.firebaseapp.com',
    storageBucket: 'canvas701.firebasestorage.app',
    measurementId: 'G-PL691BJXHZ',
  );

}